name: Build CreateAnalyzer

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: |
          ./gradlew build || (echo "Gradle wrapper missing; using Gradle via wrapper task" && ./gradlew wrapper && ./gradlew build)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CreateAnalyzer-build
          path: |
            build/libs/*.jar
            build/libs/*.sources.jar
