# .github/workflows/build.yml
name: Build CreateAnalyzer
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Validasi wrapper — non-blocking kalau jaringan fail
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Guard kalau bit eksekusi gradlew belum kepush dari Windows
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CreateAnalyzer-build
          path: |
            build/libs/*.jar
            build/libs/*.sources.jar
